project:
  type: website
  output-dir: docs

website:
  title: "My website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: project.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



